#!/usr/bin/env bash
set -u
for f in .??*; do
  [ "$f" = ".git" ] && continue
  [ "$f" = ".gitconfig.local.template" ] && continue
  [ "$f" = ".gitmodules" ] && continue
  ln -snfv ${PWD}/"$f" ~/
done
